### ISSUE TITLE
Create issues with "TODO" label, if possible

### ISSUE THREAD

**Issue by groovecoder** [mrmakeit/github-todo#31]

**Comment by Faeranne** [comment]
This has been discussed before, but to add labels would require repo permissions beyond the oauth API, and as such is not currently in consideration.

**Comment by groovecoder** [comment]
What if you just check if a "TODO" label already exists in the repo with [the GitHub Issue Labels API](https://developer.github.com/v3/issues/labels/#get-a-single-label), and then add it?

**Comment by Faeranne** [comment]
I'll look into it.

**Comment by Faeranne** [comment]
Only Collaborators can add or change labels on a issue.  Outside users cannot modify them, even on issues they open.

**Comment by groovecoder** [comment]
Ah, too bad.
