### ISSUE TITLE
github-todo-issue.herokuapp.com is down?

### ISSUE THREAD

**Issue by groovecoder** [mrmakeit/github-todo#33]
github-todo-issue.herokuapp.com doesn't return.

Webhook settings says: " Sorry, something went wrong and we weren’t able to fetch the deliveries for this hook. "

Did the url change or something?

**Comment by Faeranne** [comment]
The server was offline due to heroku issues.  I'm going to move it to the new heroku stack per their request.

**Comment by Faeranne** [comment]
I've upgraded the Heroku stack, so that shouldn't happen again.
